# syntax = docker/dockerfile:1
FROM node:20-slim

LABEL fly_launch_runtime="NestJS"

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app
COPY apps/server ./apps/server
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

WORKDIR /app/apps/server
RUN pnpm install --frozen-lockfile
RUN pnpm build

EXPOSE 8080

CMD ["pnpm", "start:prod"]
