name: Deploy client production
on: workflow_dispatch

jobs:
  build-deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Production environment
        working-directory: ./apps/client
        run: |
          touch .env.production
          echo "VITE_SERVER_API_URL=${{ secrets.CLIENT_VITE_SERVER_API_URL }}" >> .env.production

      - name: build Prod
        working-directory: ./apps/client
        run: pnpm build:prod

      - name: Publish
        working-directory: ./apps/client
        run: pnpm --package=netlify-cli dlx netlify deploy --dir=./apps/client/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.CLIENT_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.CLIENT_NETLIFY_AUTH_TOKEN }}
